config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "activities#index"

  resources :projects do
    resources :activities

    get "records", to: "records#index"
    get "reports", to: "reports#index"

    resources :building_units, only: [:edit, :update, :destroy] do
      resources :records
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :project
  has_many :records
  has_many :subcontracts
  has_many :subcontractors, through: :subcontracts

  def to_s
    "#{self.id}) #{self.name}"
  end

  def subcontractor_names
    self.subcontractors.map { |sub| sub.name }.join(", ")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/building_unit.rb
class BuildingUnit < ApplicationRecord
  belongs_to :project
  belongs_to :parent, class_name: 'BuildingUnit', optional: true, foreign_key: :building_unit_id
  has_many :children, class_name: 'BuildingUnit', dependent: :destroy
  has_many :records

  validates :name, presence: true

  scope :parents, ->(pid) { where(building_unit_id: nil, project_id: pid) }

  def all_children
    children.flat_map do |child_cat|
      child_cat.all_children << child_cat
    end
  end

=begin
  def all_children
    BuildingUnit.find_by_sql(recursive_tree_children_sql)
  end

  private

  def recursive_tree_children_sql
    columns = self.class.column_names
    columns_joined = columns.join(',')
    sql =
      <<-SQL
        WITH RECURSIVE category_tree (#{columns_joined}, level)
        AS (
          SELECT
            #{columns_joined},
            0
          FROM categories
          WHERE id = #{id}

          UNION ALL
          SELECT
            #{columns.map { |col| 'cat.' + col }.join(',')},
            ct.level + 1
          FROM categories cat, category_tree ct
          WHERE cat.category_id = ct.id
        )
        SELECT * FROM category_tree
        WHERE level > 0
        ORDER BY level, category_id, name;
      SQL
    sql.chomp
  end
=end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :activities
  has_many :building_units
  has_many :subcontractors
  has_many :subcontracts
  has_many :red_days
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :activity
  belongs_to :building_unit

  validates :activity_id, comparison: { greater_than: 0 }
  validates :end_date, comparison: { greater_than_or_equal_to: :start_date }

  def num_resources
    self.assignees.split(', ').count.to_s
  end
end

app/models/red_day.rb
class RedDay < ApplicationRecord
  belongs_to :project
end

app/models/subcontract.rb
class Subcontract < ApplicationRecord
  belongs_to :activity
  belongs_to :subcontractor
  belongs_to :project
end

app/models/subcontractor.rb
class Subcontractor < ApplicationRecord
  has_many :subcontracts
  has_many :activities, through: :subcontracts
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :find_project

  def index
  end

  def new
  end

  def create
    @activity = @project.activities.create(create_activity_params)
    redirect_to project_activities_path
  end

  def destroy
    @activity = @project.activities.find(params[:id])
    @activity.destroy
    redirect_to project_activities_path
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def create_activity_params
    params.require(:activity).permit(:name, :description, :ui_color)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/building_units_controller.rb
class BuildingUnitsController < ApplicationController
  before_action :find_project
  before_action :find_bu

  def edit
  end

  def update
    orig_name = @building_unit.name
    respond_to do |format|
      if @building_unit.update(bu_params)
        format.turbo_stream
      else
        @building_unit.name = orig_name
        format.turbo_stream
      end
    end
  end

  def destroy
    @building_unit.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_bu
    @building_unit = @project.building_units.find(params[:id])
  end

  def bu_params
    params.require(:building_unit).permit(:name, :project_id)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :find_project

  def index
    @building_units = @project.building_units
    @red_days = @project.red_days.map { |rd| rd.date }
    @records_map = {}
    @building_units.each do |bu|
      @records_map[bu.id] = bu.records
    end

    #parents = BuildingUnit.parents(params[:project_id])
    #@building_units = BuildingUnit.first.all_children
=begin
    @building_units = []
    parents.each do |bu|
      @building_units << bu.children
    end
=end
  end

  def new
    @building_unit = BuildingUnit.find(params[:building_unit_id])
    @record = Record.new(start_date: params[:date], end_date: params[:date], is_finished: false)
  end

  def create
    @building_unit = BuildingUnit.find(params[:building_unit_id])
    @record = @building_unit.records.new(record_params)
    if @record.save
      redirect_to project_records_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @building_unit = BuildingUnit.find(params[:building_unit_id])
    @record = @building_unit.records.find(params[:id])
  end

  def update
    @building_unit = BuildingUnit.find(params[:building_unit_id])
    @record = @building_unit.records.find(params[:id])
    if @record.update(record_params)
      redirect_to project_records_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @building_unit = BuildingUnit.find(params[:building_unit_id])
    @record = @building_unit.records.find(params[:id])
    @record.destroy
    redirect_to project_records_path, status: :see_other
  end

  private

  def find_project
    @project = Project.includes(:red_days).find(params[:project_id])
  end

  def record_params
    params.require(:record).permit(:activity_id, :assignees, :start_date, :end_date, :is_finished, :obs)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    # @records = @project.records
    @records = Record.all
    @current_week = DateTime.now.to_date.beginning_of_week
  end

  def paginate_prev

  end

  def paginate_next

  end

  def paginate_records(week_number)
    # TODO Change to project_week_number
    if (1 > week_number || week_number > 53)
      render json: {
        records: [],
        errors: t("error.invalid_week_number"),
      }
    end

    current_week = DateTime.now.to_date

    filter_start = current_week.beginning_of_week
    filter_end = current_week.end_of_week

    records = Record.where("start_date >= ? AND start_date <= ?", filter_start, filter_end)

    render json: {
      records: records,
      errors: nil,
    }
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def select_field_list(activities)
    activities.map { |act| [act.to_s, act.id] }.unshift(["Select activity", -1])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/building_units_helper.rb
module BuildingUnitsHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def tab_styles(name)
    if current_page?(controller: name)
      "text-green-400 transition"
    else
      "text-white hover:text-slate-400 focus:text-slate-400 transition"
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
  def is_weekend?(date)
    date.saturday? || date.sunday?
  end

  def today?(date)
    date == DateTime.now.to_date
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/activities/_activity.html.erb
<tr>
  <td><%= activity.id %></td>
  <td><%= activity.name %></td>
  <td><%= activity.planned_start_date %></td>
  <td><%= activity.planned_end_date %></td>
  <td><%= activity.start_date %></td>
  <td><%= activity.end_date %></td>
  <td>
    <span>(<%= activity.subcontractors.count %>)</span>
    <span><%= activity.subcontractor_names %></span>
  </td>
  <td><%= activity.obs %></td>
  <td>
    <%= link_to "Delete", [activity.project, activity], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure you want to delete the activity? Action may not be restored"
    } %>
  </td>
</tr>

app/views/activities/index.html.erb
<main class="container mx-auto mt-8">
  <h1 class="text-xl text-black font-bold pb-5"><%= t("pages.activities") %></h1>

  <span>Project plan</span>
  <span><%= @project.start_date %> - <%= @project.planned_end_date %></span>

  <span style="background: green; color:white;">
    <%= link_to 'New', new_project_activity_path %>
  </span>

  <table>
    <thead>
      <tr>
        <th><%= t("fields.id") %></th>
        <th><%= t("fields.name") %></th>
        <th><%= t("fields.planned_start_date") %></th>
        <th><%= t("fields.planned_end_date") %></th>
        <th><%= t("fields.start_date") %></th>
        <th><%= t("fields.end_date") %></th>
        <th><%= t("entities.subcontractor") %></th>
        <th><%= t("fields.obs") %></th>
        <th>Delete?</th>
      </tr>
    </thead>
    <tbody>
      <%= render @project.activities %>
    </tbody>
  </table>
</main>

app/views/activities/new.html.erb
<h1><%= t("actions.activity.create") %></h1>

<%= form_with model: [ @project, @project.activities.build ] do |form| %>
  <p>
    <%= form.label :name, t("fields.name") %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description, t("fields.description") %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :ui_color, t("fields.color") %><br>
    <%= form.text_area :ui_color %>
  </p>
  <p>
    <%= form.submit t("actions.activity.create") %>
  </p>
<% end %>

app/views/building_units/_building_unit.html.erb
<td class="record-name" id="<%= "#{dom_id(bu)}_td" %>">
  <%= turbo_frame_tag dom_id(bu), class: "flex items-center justify-between" do %>
    <%= bu.name %>

    <div class="flex items-center gap-x-3">
      <%= link_to t("actions.generic.rename"), edit_project_building_unit_path(bu.project_id, bu.id) %>
      <%= button_to t("actions.generic.delete"), project_building_unit_path(bu.project_id, bu.id), method: :delete %>
    </div>
  <% end %>
</td>

app/views/building_units/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{dom_id(@building_unit)}_tr" %>

app/views/building_units/edit.html.erb
<%= turbo_frame_tag dom_id(@building_unit) do %>
  <%= form_with model: [ @project, @building_unit ], data: { controller: "closeescapeinput" } do |form| %>
    <div class="flex items-center justify-between">
      <%= form.text_field :name,
        autofocus: true,
        class: "w-full",
        data: {
          closeescapeinput_target: "input",
          action: "keyup->closeescapeinput#escClose",
        }
      %>
      <%= form.submit t("actions.generic.update") %>
    </div>
  <% end %>
<% end %>

app/views/building_units/index.html.erb
<h1>Progress</h1>

<span>Project plan</span>
<span><%= @project.start_date %> - <%= @project.planned_end_date %></span>

<table>
  <thead>
    <tr>
      <%# First column %>
      <th>Building Unit</th>

      <%# Rest of columns (dates) %>
      <% date_ptr = @project.start_date %>
      <% while date_ptr <= @project.planned_end_date do %>
        <th><%= date_ptr.day %></th>
        <% date_ptr = date_ptr.next_day %>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @building_units.each do |bu| %>
      <tr>
        <%# First column %>
        <td><%= bu.name %></td>

        <%# Rest of columns (dates) %>
        <% date_ptr = @project.start_date %>
        <% while date_ptr <= @project.planned_end_date do %>
          <td>
            <button>
              -
            </button>
          </td>
          <% date_ptr = date_ptr.next_day %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/building_units/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@building_unit)}_td" do %>
  <%= render "building_unit", bu: @building_unit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Madrugapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/parts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/parts/_navbar.html.erb
<header class="bg-slate-900">
  <div class="container mx-auto py-5 flex items-center justify-between">
    <nav class="flex items-center gap-4 text-white">
      <%= link_to '/' do %>
        <%= image_tag '', class: "w-32 aspect-[5/2]" %>
      <% end %>

      <%= link_to project_activities_path do %>
        <strong><%= @project.name %></strong>
      <% end %>

      &#62;

      <ul class="flex gap-4">
        <li>
          <%= link_to t("pages.activities"), project_activities_path, class: tab_styles(:activities) %>
        </li>
        <li>
          <%= link_to t("pages.progress"), project_records_path, class: tab_styles(:records) %>
        </li>
        <li>
          <%= link_to t("pages.reports"), project_reports_path, class: tab_styles(:reports) %>
        </li>
      </ul>
    </nav>

    <div>
      <%= image_tag "avatar.jpeg", class: "w-10 h-10 border border-solid border-blue-100 rounded-full" %>
    </div>
  </div>
</header>

app/views/records/_date.html.erb
<% project = local_assigns[:project] %>
<% bu = local_assigns[:bu] %>
<% record = local_assigns[:record] %>
<% date = local_assigns[:date] %>
<% is_red_day = local_assigns[:is_red_day] %>

<% if is_red_day || is_weekend?(date) %>
  <td class="record record-off"></td>
<% elsif record.nil? %>
  <td class="record record-empty">
    <%= link_to "",
      new_project_building_unit_record_path(@project, bu, date: date)
    %>
  </td>
<% else %>
  <td class="record record-started <%= record.is_finished ? "record-finished" : nil %>">
    <%= link_to record.num_resources,
      edit_project_building_unit_record_path(@project, bu, record)
    %>
  </td>
<% end %>

app/views/records/_date_header.html.erb
<%
  date = local_assigns[:date]
  is_red_day = local_assigns[:is_red_day]
%>
<% class_name = today?(date) ?
  "record-header-today"
: is_red_day || is_weekend?(date) ?
  "record-header-off"
: nil
%>

<th class="record-header <%= class_name %>">
  <div><%= t("days.#{date.strftime("%a").downcase}") %></div>
  <div><%= date.day %></div>
</th>

app/views/records/_form.html.erb
<% action = local_assigns[:action] %>

<%= form_with model: [ @project, @building_unit, @record ] do |form| %>
  <p>
    <%= form.label :activity_id, t("entities.activity") %><br>
    <%= form.select :activity_id, select_field_list(@project.activities) %>
  </p>
  <p>
    <%= label :subcontractors, t("entities.subcontractors") %><br>
    <%= text_field nil,
      :subcontractors,
      value: !@record.activity.nil? ? @record.activity.subcontractor_names : nil,
      disabled: true
    %>
  </p>
  <p>
    <%= form.label :assignees, t("fields.assignees") %><br>
    <%= form.text_area :assignees %>
  </p>
  <p>
    <%= form.label :start_date, t("fields.start_date") %><br>
    <%= form.date_field :start_date %>
  </p>
  <p>
    <%= form.label :end_date, t("fields.end_date") %><br>
    <%= form.date_field :end_date %>
  </p>
  <p>
    <%= form.label :is_finished, t("fields.finished") %><br>
    <%= form.check_box :is_finished %>
  </p>
  <p>
    <%= form.label :obs, t("fields.obs") %><br>
    <%= form.text_area :obs, size: "70x5" %>
  </p>
  <p>
    <%= form.submit t("actions.record.#{action}") %>
  </p>
<% end %>

app/views/records/edit.html.erb
<h1><%= t("actions.record.edit") %></h1>

<%= link_to t("nav.back"), project_records_path %>

<%= render partial: "form", locals: { action: :update } %>

<%= form_with method: "delete", model: [ @project, @building_unit, @record ] do |form| %>
  <%= form.submit t("actions.record.delete") %>
<% end %>

app/views/records/index.html.erb
<main>
  <div class="container mx-auto mt-8 pb-4">
    <h1 class="text-xl text-black font-bold pb-5"><%= t("pages.progress") %></h1>

    <span>Project plan</span>
    <span><%= @project.start_date %> - <%= @project.planned_end_date %></span>
  </div>

  <div class="max-w-full overflow-auto">
    <table class="records">
      <thead>
        <tr>
          <%# First column %>
          <th class="record-header-name"><%= t("entities.bu") %></th>

          <%# Rest of columns (dates) %>
          <% date = @project.start_date %>
          <% while date <= @project.planned_end_date do %>
            <%= render partial: "date_header", locals: {
              date: date,
              is_red_day: @red_days.include?(date)
            } %>
            <% date = date.next_day %>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @building_units.each do |bu| %>
          <tr id="<%= "#{dom_id(bu)}_tr" %>">
            <%# First column %>
            <%= render "building_units/building_unit", bu: bu %>

            <%# Rest of columns (dates) %>
            <% date = @project.start_date %>
            <% while date <= @project.planned_end_date do %>
              <% records_for_bu = @records_map[bu.id] %>
              <% records_for_date = records_for_bu.filter { |rec| rec.start_date == date }%>
              <% record = records_for_date[0] %>

              <%= render partial: "date", locals: {
                project: @project,
                bu: bu,
                record: record,
                date: date,
                is_red_day: @red_days.include?(date)
              } %>

              <% date = date.next_day %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/records/new.html.erb
<h1><%= t("actions.record.create") %></h1>

<%= link_to t("nav.back"), project_records_path %>

<%= render partial: "form", locals: { action: :create } %>

app/views/reports/index.html.erb
<h1><%= t("pages.reports")%></h1>

<span>Project plan</span>
<span><%= @project.start_date %> - <%= @project.planned_end_date %></span>

<div class="week-selector">
  <button class="week-selector-btn">
    &#60;
    <span class="vh">Prev</span>
  </button>
  <span>Week <%= @current_week.strftime('%-V').to_i %></span>
  <button class="week-selector-btn">
    <span class="vh">Next</span>
    &#62;
  </button>
</div>

<ul>
  <% @project.subcontractors.each do |sub| %>
    <li>
      <h2><%= sub.name %></h2>
      <ul>
        <% sub.activities.each do |act| %>
          <% activity_records = @records.select { |rec| rec.activity_id == act.id } %>
          <% unless activity_records.empty? %>
            <li>
              <h3><%= act.name %></h3>
              <% activity_records.each do |ar| %>
                <div><%= ar.num_resources %></div>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>